# Generated by Django 3.1.5 on 2021-01-06 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name="artist's stage name")),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('spotify_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('youtube_url', models.URLField(blank=True)),
                ('spotify_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('released_in', models.DateField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('spotify_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SongArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('RP', 'Rappeer'), ('BP', 'Beat by')], default='RP', max_length=2, verbose_name='Rap / Beat')),
                ('feat', models.BooleanField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhh.artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhh.song')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(related_name='songs', through='dhh.SongArtist', to='dhh.Artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dhh.label'),
        ),
        migrations.AddField(
            model_name='song',
            name='languages',
            field=models.ManyToManyField(to='dhh.Language'),
        ),
        migrations.AddField(
            model_name='artist',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dhh.label'),
        ),
    ]
