# Generated by Django 3.1.5 on 2021-01-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songartist',
            name='role',
            field=models.CharField(choices=[('RP', 'Rapper'), ('BP', 'Beat by'), ('CS', 'Chorus by')], default='RP', max_length=2, verbose_name='Rap / Beat'),
        ),
    ]
