# Generated by Django 3.1.5 on 2021-01-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhh', '0002_auto_20210107_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='released_in',
            field=models.DateField(null=True),
        ),
    ]
